name: ci

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'

jobs:
  linux-tests:
    strategy:
      fail-fast: false
      matrix:
        go-version: [1.16.x, 1.17.x]
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Set up Go ${{ matrix.go }}
      uses: actions/setup-go@v2.1.4
      with:
        go-version: ${{ matrix.go }}
    - name: Install fuse
      run: sudo apt-get update && sudo apt-get install -y fuse3 libfuse-dev
    - name: Build
      run: go build ./...
    - name: Run tests
      run: go test -p 1 -count 1 -v -cover ./...
